export const AllPlansContent = [
  {
    planName: "Bullet",
    plateform: "Plateform 1",
    sellingPrice: "100",
    originalPrice: "99",
    duration: "1 Month",
    descriptionEnumList: ["Unlimited Support", "24/7 Access"],
    notIncludedBenefits: ["No Free Trial"],
    popular: false,
  },
  {
    planName: "Turbo",
    plateform: "Plateform 2",
    sellingPrice: "500",
    originalPrice: "149",
    duration: "3 Months",
    descriptionEnumList: [
      "Unlimited Support",
      "Priority Access",
      "Profile Verification",
    ],
    notIncludedBenefits: ["No Free Trial"],
    discount: "42%",
    popular: true,
  },
  {
    planName: "Hyper",
    plateform: "Plateform 3",
    sellingPrice: "1000",
    originalPrice: "399",
    duration: "6 Months",
    descriptionEnumList: [
      "Unlimited Support",
      "Priority Access",
      "Profile Verification",
      "Access to Premium Features",
    ],
    notIncludedBenefits: ["No Free Trial"],
    discount: "59%",
    popular: true,
  },
];
